title: "The Data Dictionary"
description: "ERP Metadata Portal by Altitude House Consulting"
remote_theme: just-the-docs/just-the-docs
logo: /assets/logo.png
search_enabled: true
color_scheme: light

